
name: unified-runtime-coverity
# It runs static analysis build - Coverity. It requires special token (set in CI's secret).

on: [push, pull_request]
  # schedule:
    # run this job at 00:00 UTC everyday
    # - cron:  '0 0 * * *'

env:
  REPO:           unified-runtime
  GITHUB_REPO:    oneapi-src/unified-runtime
  WORKDIR:   ${{ github.workspace }}
  COVERITY_SCAN_NOTIFICATION_EMAIL:  ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
  COVERITY_SCAN_TOKEN:               ${{ secrets.COVERITY_SCAN_TOKEN }}

jobs:
  linux:
    name: Coverity
    runs-on: ubuntu-latest
  
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
       
      - name: Install pip packages
        run: pip install -r third_party/requirements.txt

      - name: Configure CMake
        run: cmake -B $WORKDIR/build -DUR_ENABLE_TRACING=ON -DUR_DEVELOPER_MODE=ON -DUR_BUILD_TESTS=ON -DUR_FORMAT_CPP_STYLE=ON

      - name: Generate source from spec, check for uncommitted diff
        run: cmake --build $WORKDIR/build --target check-generated

      # coverity workflow should just reuse (pull) the most recent, available image
      #- name: Run the build
      # run: cd $WORKDIR && ${{ matrix.CONFIG }} ./build.sh

