#
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
name: unified-runtime-coverity
# It runs static analysis build - Coverity. It requires special token (set in CI's secret).

on:
  workflow_dispatch:
  schedule:
    # run this job at 00:00 UTC everyday
    - cron:  '0 0 * * *'

env:
  REPO:           unified-runtime
  GITHUB_REPO:    oneapi-src/unified-runtime
  WORKDIR:   ${{ github.workspace }}
  COVERITY_SCAN_NOTIFICATION_EMAIL:  ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
  COVERITY_SCAN_TOKEN:               ${{ secrets.COVERITY_SCAN_TOKEN }}
  COVERITY_SCAN_PROJECT_NAME:        ${{ github.repository }}
  COVERITY_SCAN_BUILD_COMMAND:       "make"
  COVERITY_SCAN_BRANCH_PATTERN:      "main"
  TRAVIS_BRANCH:                     "main"
  TRAVIS_PULL_REQUEST:               "false"

jobs:
  linux:
    name: Coverity
    runs-on: ubuntu-latest
  
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
       
      - name: Install pip packages
        run: pip install -r third_party/requirements.txt

      - name: Configure CMake
        run: cmake -B $WORKDIR/build -DUR_ENABLE_TRACING=ON -DUR_DEVELOPER_MODE=ON -DUR_BUILD_TESTS=ON -DUR_FORMAT_CPP_STYLE=ON

      - name: Generate source from spec, check for uncommitted diff
        run: |
          cmake --build $WORKDIR/build --target check-generated
          echo $COVERITY_SCAN_PROJECT_NAME
          echo $COVERITY_SCAN_BUILD_COMMAND
          echo "----------------------------- XXX"
      - name: Run Coverity
        run: |
          cd $WORKDIR/build
          echo "-----HIM"
          pwd
          echo "-----HIM"
          wget https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh
          echo "-----HIM"
          ls
          pwd
          echo "-----HIM"
          patch < "../.github/scripts/0001-travis-fix-travisci_build_coverity_scan.sh.patch"
          bash ./travisci_build_coverity_scan.sh
